import type { Metadata } from "next";

import "./globals.css";
import ThemeProvider from "./../providers/ThemeProvider";

export const metadata: Metadata = {
  title: "Tabseer Inc",
  description: "Generated by create next app",
};

export type ChildrenType = {
  children: React.ReactNode;
};

const RootLayout = ({ children }: ChildrenType) => {
  return (
    <>
      <html lang="en" suppressHydrationWarning={true}>
        <link rel="icon" href="/favicon.svg" sizes="any" />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </>
  );
};

export default RootLayout;
